// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace BloggingSite.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190409121921_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BloggingSite.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogPostBlogID");

                    b.Property<string>("Name");

                    b.HasKey("TopicId");

                    b.HasIndex("BlogPostBlogID");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("WebApplication.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("BlogID");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("BloggingSite.Models.Topic", b =>
                {
                    b.HasOne("WebApplication.Models.BlogPost")
                        .WithMany("Topics")
                        .HasForeignKey("BlogPostBlogID");
                });
#pragma warning restore 612, 618
        }
    }
}
